version: '3'

services:
  
  nestfinderapiservice:
    image: nestfinderapiservice
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
      args:
        APP_ENV: ${APP_ENV}
    environment:
      NODE_ENV: ${NODE_ENV}
      APP_ENV: ${APP_ENV}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      DB_HOST: mysqldb
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}
    volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
    command: sh -c 'if [ "$NODE_ENV" = "production" ]; then yarn start; else yarn dev; fi'
    ports:
      - ${PORT}:3000
    depends_on:
      - redis
      - mysqldb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "${NGINX_PORT}:80"
      # - "443:443"  # Uncomment for HTTPS
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/ssl:/etc/nginx/ssl  # Uncomment for HTTPS certificates
    depends_on:
      - nestfinderapiservice
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: app-network:redis:${REDIS_PORT}
    ports:
      - "${REDIS_UI_PORT}:8081"
    depends_on:
      - redis
    networks:
      - app-network

  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  db_data:
  
  
